categories = ['business', 'entertainment', 'general', 'health', 'science', 'sports', 'technology']

countries = {'ae': 'United Arab Emirates',
             'ar': 'Argentina',
             'at': 'Austria',
             'au': 'Australia',
             'be': 'Belgium',
             'bg': 'Bulgaria',
             'br': 'Brazil',
             'ca': 'Canada',
             'ch': 'Switzerland',
             'cn': 'China',
             'co': 'Colombia',
             'cu': 'Cuba',
             'cz': 'Czechia',
             'de': 'Germany',
             'eg': 'Egypt',
             'fr': 'France',
             'gb': 'Great Britain',
             'gr': 'Greece',
             'hk': 'Hong Kong',
             'hu': 'Hungary',
             'id': 'Indonesia',
             'ie': 'Ireland',
             'il': 'Israel',
             'in': 'India',
             'it': 'Italy',
             'jp': 'Japan',
             'kr': 'Korea (Republic of)',
             'lt': 'Lithuania',
             'lv': 'Latvia',
             'ma': 'Morocco',
             'mx': 'Mexico',
             'my': 'Malaysia',
             'ng': 'Nigeria',
             'nl': 'Netherlands',
             'no': 'Norway',
             'nz': 'New Zealand',
             'ph': 'Philippines',
             'pl': 'Poland',
             'pt': 'Portugal',
             'ro': 'Romania',
             'rs': 'Serbia',
             'ru': 'Russian Federation',
             'sa': 'Saudi Arabia',
             'se': 'Sweden',
             'sg': 'Singapore',
             'si': 'Slovenia',
             'sk': 'Slovakia',
             'th': 'Thailand',
             'tr': 'Turkey',
             'tw': 'Taiwan',
             'ua': 'Ukraine',
             'us': 'United States of America',
             've': 'Venezuela',
             'za': 'South Africa'}

languages = {'ar': 'Arabic',
             'de': 'German',
             'en': 'English',
             'es': 'Spanish',
             'fr': 'French',
             'he': 'Hebrew',
             'it': 'Italian',
             'nl': 'Dutch',
             'no': 'Norwegian',
             'pt': 'Portuguese',
             'ru': 'Russian',
             'se': 'Sami',
             'ud': '? (UD)',
             'zh': 'Chinese'}
